// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class Agent extends Trader{
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private Infrastructure[] buildingsOwned;
	/**
	 * 
	 */
	private Infrastructure[] roadsOwned;
	/**
	 * 
	 */
	private int roadsLeft;
	/**
	 * 
	 */
	private int citiesLeft;
	/**
	 * 
	 */
	private int settlementsLeft;
	/**
	 * 
	 */
	public Infrastructure[] infrastructure;

	/**
	 * 
	 */
	public void Agent(){
	}

	/**
	 * 
	 */
	public void buildRoad(){
	}

	/**
	 * 
	 */
	public void buildCity(){
	}

	/**
	 * 
	 */
	public void buildSettlement(){
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints(){
	}
}
