// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class Bank extends Trader{
	/**
	 * 
	 */
	public void Bank(){
	}
}
