// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class Board{
	/**
	 * 
	 */
	private HexTile[] tiles;
	/**
	 * 
	 */
	public HexTile[] hextile;

	/**
	 * 
	 */
	public void Board(){
	}

	/**
	 * 
	 * @param token 
	 * @return 
	 */
	public HexTile[] getResourceProdTile(int token){
	}
}
