// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public interface Card{
	/**
	 * 
	 * @return 
	 */
	public String getCardType();
}
