// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class City extends Infrastructure{
	/**
	 * 
	 * @param owner 
	 */
	public void City(Trader owner){
	}
}
