// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public interface Dice{
	/**
	 * 
	 */
	public MultiDice[] multidice;

	/**
	 * 
	 * @return 
	 */
	public int roll();
}
