// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class Edge extends Location{
	/**
	 * 
	 */
	private int start;
	/**
	 * 
	 */
	private int end;

	/**
	 * 
	 * @param start 
	 * @param end 
	 */
	public void Edge(int start, int end){
	}
}
