// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class Game{
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Trader[] agents;
	/**
	 * 
	 */
	private Trader bank;
	/**
	 * 
	 */
	private Dice dice;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Trader[] trader;
	/**
	 * 
	 */
	public Dice dice;

	/**
	 * 
	 * @param rounds 
	 */
	public void Game(int rounds){
	}

	/**
	 * 
	 */
	public void run(){
	}

	/**
	 * 
	 */
	private void produceResource(){
	}

	/**
	 * 
	 */
	private void build(){
	}
}
