// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class HexTile{
	/**
	 * 
	 */
	private ResourceType resource;
	/**
	 * 
	 */
	private int landTileID;
	/**
	 * 
	 */
	private int token;
	/**
	 * 
	 */
	private Location[] nodes;
	/**
	 * 
	 */
	private Location[] edges;
	/**
	 * 
	 */
	public Location[] location;
	/**
	 * 
	 */
	public ResourceType resourcetype;

	/**
	 * 
	 * @param resource 
	 * @param landTileID 
	 * @param token 
	 * @param nodes 
	 * @param edges 
	 */
	public HexTile(ResourceType resource, int landTileID, int token, Location[] nodes, Location[] edges){
	}

	/**
	 * 
	 * @return 
	 */
	public Location[] getNodes(){
	}

	/**
	 * 
	 * @return 
	 */
	public Location[] getEdges(){
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType(){
	}

	/**
	 * 
	 * @return 
	 */
	public int getlandTileID(){
	}

	/**
	 * 
	 * @return 
	 */
	public int getToken(){
	}
}
