// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public abstract class Infrastructure{
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private Agent owner;
	/**
	 * 
	 */
	private Location location;
	/**
	 * 
	 */
	public Location location;

	/**
	 * 
	 * @param victoryPoints 
	 * @param owner 
	 */
	public void Infrastructure(int victoryPoints, Trader owner){
	}

	/**
	 * 
	 * @param location 
	 */
	public abstract void build(Location location);

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints(){
	}

	/**
	 * 
	 * @return 
	 */
	public int getOwner(){
	}

	/**
	 * 
	 * @param location 
	 */
	public void setLocation(Location location){
	}

	/**
	 * 
	 * @return 
	 */
	public Location getLocation(){
	}
}
