// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public abstract class Location{
	/**
	 * 
	 */
	private boolean occupied;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied(){
	}

	/**
	 * 
	 */
	public void setOccupied(){
	}

	/**
	 * 
	 */
	public void Location(){
	}
}
