// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class MultiDice{
	/**
	 * 
	 */
	private Dice[] diceSet;

	/**
	 * 
	 * @param numOfDice 
	 */
	public void MultiDice(int numOfDice){
	}

	/**
	 * 
	 * @return 
	 */
	public int roll(){
	}
}
