// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class Node extends Location{
	/**
	 * 
	 */
	private int id;

	/**
	 * 
	 * @param id 
	 */
	public void Node(int id){
	}
}
