// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class RegularDie{
	/**
	 * 
	 */
	private undef random;

	/**
	 * 
	 */
	public void RegularDie(){
	}

	/**
	 * 
	 * @return 
	 */
	public int roll(){
	}
}
