// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public class ResourceCard{
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	public ResourceType resourcetype;

	/**
	 * 
	 */
	public void ResourceCard(){
	}

	/**
	 * 
	 * @return 
	 */
	public String getCardType(){
	}
}
