// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan_Diagram;

/************************************************************/
/**
 * 
 */
public abstract class Trader{
	/**
	 * 
	 */
	private int[] resourceCount;
	/**
	 * 
	 */
	private Card[] resourceHand;
	/**
	 * 
	 */
	public Card[] card;

	/**
	 * 
	 */
	public void Trader(){
	}

	/**
	 * 
	 * @param newCard 
	 */
	public void addCard(Card newCard){
	}

	/**
	 * 
	 * @return 
	 */
	public Card removeCard(){
	}
}
