// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/

import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

/**
 * This class represents an agent, or a player in the simulated catan game. 
 */
public abstract class Agent extends Trader {

	private int id;
	private int victoryPoints;
	private int roadsLeft;
	private int citiesLeft;
	private int settlementsLeft;
	private int infraCount;
	private Colour colour;
	private Infrastructure[] infrastructure;


	public Agent(int id){
		this.id = id;
		this.roadsLeft = 15;
		this.citiesLeft = 4;
		this.settlementsLeft = 5;
		this.infraCount = 0;
		this.victoryPoints = 0;
		this.colour = Colour.getColour(id);
        this.infrastructure = new Infrastructure[24];
	}

	public void buildRoad(Location location){
		if (roadsLeft <= 0){
			throw new IllegalStateException("There are no roads left to build. Sorry!");
		}

		Road road = new Road(this);
		road.build(location);

		infrastructure[infraCount++] = road;
		roadsLeft--;
	}

	public void buildCity(Location location) {
		if (citiesLeft <= 0) {
			throw new IllegalStateException("There are no cities left to build.");
		}

		//Create the city object
		City city = new City(this);

		//Instead of just adding it to the end of the array,
		//we find the settlement at this location and replace it.
		boolean replaced = false;
		for (int i = 0; i < infraCount; i++) {
			//If we find the settlement belonging to this player at this location
			if (infrastructure[i] instanceof Settlement && infrastructure[i].getLocation().equals(location)) {
				infrastructure[i] = city; //Swap it in the array
				replaced = true;
				break;
			}
		}

		//Strict Rule Check: If we didn't find a settlement to replace, this build would be illegal
		if (!replaced) {
			throw new IllegalStateException("Cannot build a city: No settlement exists at this location.");
		}

		//Set the location and update counts
		city.setLocation(location);
		citiesLeft--;
		settlementsLeft++; //Give the settlement piece back to the player's supply
	}


	public void buildSettlement(Location location){
		if (settlementsLeft <= 0){
			throw new IllegalStateException("There are no settlements left to build. Sorry!");
		}

		Settlement settlement = new Settlement(this);
		settlement.build(location);

		infrastructure[infraCount++] = settlement;
		settlementsLeft--;
		
	}

	private int calculateVictoryPoints() {
		int total = 0;
		for (int i = 0; i < infraCount; i++) {
			// This calls Settlement.getVictoryPoints (1) or City.getVictoryPoints (2)
			total += infrastructure[i].getVictoryPoints();
		}
		this.victoryPoints = total;
		return victoryPoints;
	}

	public boolean canAfford(int toBuild) {
		// 0: Road, 1: Settlement, 2: City
		ResourceType[][] costs = {
				{ResourceType.BRICK, ResourceType.LUMBER},
				{ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL},
				{ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE}
		};

		// Bounds check to prevent crashes
		if (toBuild < 0 || toBuild >= costs.length) return false;

		ResourceType[] recipe = costs[toBuild];

		// We use getResourceCount() which returns the int[] array
		int[] original = this.getResourceCount();
		int[] temp = new int[original.length];

		// Copy current counts to a temp array so we don't accidentally deduct them
		System.arraycopy(original, 0, temp, 0, original.length);

		for (ResourceType type : recipe) {
			int index = type.getIndex();
			temp[index]--;

			if (temp[index] < 0) {
				return false; // Not enough of this resource
			}
		}
		return true; // Agent has everything required
	}


	public int getVictoryPoints(){
		return calculateVictoryPoints(); //calls the helper method above to get the victoryPoints
	}

	public int getInfraCount(){
		return infraCount;
	}

    public int getId(){ //CH - new method
        return id;
    }

	public String getColourName(){
		return this.colour.name();
	}
    public Infrastructure[] getInfrastructure(){//CH
        return infrastructure;
    }

    public List<Card> discardHalfOfHand(Random random){//CH2
        List<Card> discardedCards = new ArrayList<>();
        int discardCount = getTotalCardCount() / 2;

        for (int i = 0; i < discardCount; i++){
            discardedCards.add(removeRandomCard(random));
        }
        return discardedCards;
    }

	//For City class (NOT IN USE RIGHT NOW)
	//Overwrite the Settlement at that specific spot in the array - effectively deletes the Settlement from the game state
	public void replaceInfrastructure(int index, Infrastructure newInfra) {
		if (index >= 0 && index < infraCount) {
			this.infrastructure[index] = newInfra;
		}
	}

	public boolean mustSpendCards(){
		return getTotalCardCount() > 7;
	}

	//Methods to be overridden in HumanAgent and RandomAgent
	public abstract void takeTurn(Game game, Scanner scanner);

	// The following four methods are added so the undo/redo mechanism works and respects the encapsulation principle
	public void restoreRoad() {
		roadsLeft++;
	}

	public void restoreSettlement() {
		settlementsLeft++;
	}

	public void restoreCity() {
		citiesLeft++;
		settlementsLeft--;
	}

    public void decrementInfraCount() {
        infraCount--;
    }
}//end of Agent() Class
