// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.*;

/**
 * This class represents an agent, or a player in the simulated catan game.
 */
public abstract class Agent extends Trader {

	private int id;
	private int victoryPoints;
	private int roadsLeft;
	private int citiesLeft;
	private int settlementsLeft;
	private int infraCount;
	private Colour colour;
	private Infrastructure[] infrastructure;

	private boolean hasLongestRoad;
	//Key: A node ID
	//Value: A Set of all node IDs that are connected to this node via your roads
	protected Map<Integer, Set<Integer>> roadGraph = new HashMap<>();


	private ResourceType[][] COSTS = {
			{ResourceType.BRICK, ResourceType.LUMBER},                                          // 0: Road
			{ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL},   // 1: Settlement
			{ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE} // 2: City
	};

	public Agent(int id){
		this.id = id;
		this.roadsLeft = 15;
		this.citiesLeft = 4;
		this.settlementsLeft = 5;
		this.infraCount = 0;
		this.victoryPoints = 0;
		this.colour = Colour.getColour(id);
		this.infrastructure = new Infrastructure[24];
		hasLongestRoad = false;
	}

	public void buildRoad(Location location){
		if (roadsLeft <= 0){
			throw new IllegalStateException("There are no roads left to build. Sorry!");
		}

		Road road = new Road(this);
		road.build(location);

		infrastructure[infraCount++] = road;
		roadsLeft--;
		int startId = ((Edge) location).getStart();
		int endId = ((Edge) location).getEnd();

		//add connection both ways
		roadGraph.putIfAbsent(startId, new HashSet<>());
		roadGraph.putIfAbsent(endId, new HashSet<>());

		//bidirectional connections
		roadGraph.get(startId).add(endId); // Add startId NODE to node endId's connections
		roadGraph.get(endId).add(startId); // Add endId NODE to node startId's connections
	}

	public void buildCity(Location location) {
		if (citiesLeft <= 0) {
			throw new IllegalStateException("There are no cities left to build.");
		}

		//Create the city object
		City city = new City(this);

		//Instead of just adding it to the end of the array,
		//we find the settlement at this location and replace it.
		boolean replaced = false;
		for (int i = 0; i < infraCount; i++) {
			//If we find the settlement belonging to this player at this location
			if (infrastructure[i] instanceof Settlement && infrastructure[i].getLocation().equals(location)) {
				infrastructure[i] = city; //Swap it in the array
				replaced = true;
				break;
			}
		}

		//Strict Rule Check: If we didn't find a settlement to replace, this build would be illegal
		if (!replaced) {
			throw new IllegalStateException("Cannot build a city: No settlement exists at this location.");
		}

		//Set the location and update counts
		city.setLocation(location);
		citiesLeft--;
		settlementsLeft++; //Give the settlement piece back to the player's supply
	}


	public void buildSettlement(Location location){
		if (settlementsLeft <= 0){
			throw new IllegalStateException("There are no settlements left to build. Sorry!");
		}

		Settlement settlement = new Settlement(this);
		settlement.build(location);

		infrastructure[infraCount++] = settlement;
		settlementsLeft--;

	}

	private int calculateVictoryPoints() {
		int total = 0;
		for (int i = 0; i < infraCount; i++) {
			// This calls Settlement.getVictoryPoints (1) or City.getVictoryPoints (2)
			total += infrastructure[i].getVictoryPoints();
		}
		this.victoryPoints = total;
		return victoryPoints;
	}

	public boolean canAfford(int toBuild) {
		if (toBuild < 0 || toBuild >= COSTS.length) return false;

		int[] temp = this.getResourceCount().clone();

		for (ResourceType type : COSTS[toBuild]) {
			if (--temp[type.getIndex()] < 0) return false;
		}
		return true;
	}

	/**
	 * Pays the cost of building toBuild by transferring cards from this agent to the bank.
	 * Caller must verify canAfford() before calling this.
	 */
	public void pay(int toBuild, Trader bank) {
		for (ResourceType type : COSTS[toBuild]) {
			Card card = this.removeCard(type);
			if (card != null) bank.addCard(card);
		}
	}


	public int getVictoryPoints(){
		return calculateVictoryPoints(); //calls the helper method above to get the victoryPoints
	}

	public int getInfraCount(){
		return infraCount;
	}

	public int getId(){
		return id;
	}

	public String getColourName(){
		return this.colour.name();
	}
	public Infrastructure[] getInfrastructure(){
		return infrastructure;
	}

	public List<Card> discardHalfOfHand(Random random){
		List<Card> discardedCards = new ArrayList<>();
		int discardCount = getTotalCardCount() / 2;

		for (int i = 0; i < discardCount; i++){
			discardedCards.add(removeRandomCard(random));
		}
		return discardedCards;
	}

	public boolean mustSpendCards(){
		return getTotalCardCount() > 7;
	}

	//Methods to be overridden in HumanAgent and RandomAgent
	public abstract void takeTurn(GameManager manager, Scanner scanner);

	// The following four methods are added so the undo/redo mechanism works and respects the encapsulation principle
	public void restoreRoad() {
		roadsLeft++;
	}

	public void restoreSettlement() {
		settlementsLeft++;
	}

	public void restoreCity() {
		citiesLeft++;
		settlementsLeft--;
	}

	public void decrementInfraCount() {
		infraCount--;
	}
	public int getLongestRoadLength(GameManager game){
		int maxLength = 0;

		for (int i = 0; i < getInfraCount(); i++) {
			Infrastructure infra = getInfrastructure()[i];

			if (infra instanceof Road){
				Edge startEdge = (Edge) infra.getLocation();

				Set<Edge> usedEdges = new HashSet<>();
				maxLength = Math.max(maxLength, dfsEdge(startEdge, usedEdges, game, -1));
			}
		}
		return maxLength;
	}//end of getLongestRoadLength()


	//Find the length of the longest road
	private int dfsEdge(Edge current, Set<Edge> usedEdges, GameManager game, int cameFromNode){
		usedEdges.add(current);
		int max = 1;

		int[] nodes = {current.getStart(), current.getEnd()};

		for (int node : nodes) {
			//Prevent going back through same node
			if (node == cameFromNode) continue;

			if (game.isBlocked(node, this)) continue; //cut off by another player's settlement/city


			for (Edge next : game.getBoard().getEdgesFromNode(node)){
				if (usedEdges.contains(next)) continue;
				if (!isMyRoad(next)) continue;

				max = Math.max(max, 1 + dfsEdge(next, usedEdges, game, node));
			}
		}
		usedEdges.remove(current);
		return max;
	}//end of dfsEdge()

	public boolean isMyRoad(Edge edge){
		for (int i = 0; i < getInfraCount(); i++){
			Infrastructure infra = getInfrastructure()[i];

			if (infra instanceof Road && infra.getLocation() == edge){
				return true;
			}
		}
		return false;
	}//end of isMyRoad()

	public boolean hasLongestRoad(){
		return hasLongestRoad;
	}

	public void setHasLongestRoad(boolean a){
		hasLongestRoad = a;
	}

	public int getRoadsLeft(){
		return roadsLeft;
	}

	public int getCitiesLeft(){
		return citiesLeft;
	}
	public int getSettlementsLeft(){
		return settlementsLeft;
	}
}//end of Agent() Class
