// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import org.json.JSONObject;

/**
 * A concrete subclass of infrastructure. A type of infrastructure worth 2 VP that can be built by a player.
 */
public class City extends Infrastructure {
    public City(Agent owner){
        super(2, owner); //City gives 2 VP
    }

    @Override
    public void build(Location location) {
        if (!(location instanceof Node)) {
            throw new IllegalStateException("A city must be placed on a Node.");
        }

        //Update the location
        super.setLocation(location);

    }

    @Override
    public String getInfraName(){
        return "CITY";
    }

    @Override
    public JSONObject toJSON() {
        // "node" : nodeID, "owner": colour, type: "CITY"
        JSONObject cityObj = new JSONObject();
        int nodeID;
        if (this.getLocation() instanceof Node){
            nodeID = ((Node)this.getLocation()).getId();
        }
        else {
            return null;
        }
        cityObj.put("node", nodeID);
        cityObj.put("owner", this.getOwner().getColourName());
        cityObj.put("type", "CITY");

        return cityObj;
    }
}//end of City() class