// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/**
 * A class to represent the edges of a tile.
 */
public class Edge extends Location {
	private int start;
	private int end;

	public Edge(int start, int end){
        this.start = start;
        this.end = end;
	}

    public int getStart(){
        return start;
    }
    public int getEnd(){
        return end;
    }
}//end of Edge() class
