// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.io.IOException;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Game{
    private int maxRounds;
    private int currentRound;
    private Board board;
    private Trader[] agents;
    private Trader bank;

    private Dice dice;

    private Random random;

    private Trader currentPlayer;
    private JsonWriter writer;
    private Process visualizer;

    private int minForLongestRoad = 5;//UML
    private Agent currentLongestRoadOwner;//UML
    private int currentLongestRoadLen;//UML

    @SuppressWarnings("java:S2245") // Pseudorandom RNG okay for game logic
    public Game(int rounds, int numPlayers, boolean demoMode){
        this.maxRounds = rounds;
        agents = new Agent[numPlayers];

        agents[0] = new HumanAgent(1); //first player is human

        if (demoMode) this.random = new Random(12);

        else this.random = new Random();

        dice = new MultiDice(2, random);

        for (int i = 1; i < numPlayers; i++){
            if (demoMode){
                agents[i] = new RandomAgent(i + 1, new Random((long) i + 20)); //the other players are computers
            }
            else{
                agents[i] = new RandomAgent(i + 1, new Random()); //the other players are computers
            }
        }
        board = new Board();
        bank = new Bank();

        currentLongestRoadOwner = null;
        currentLongestRoadLen = 0;

        writer = new JsonWriter("state.json", "visualizer/base_map.json");
        launchVisualizer();
    }//end of Game constructor

    public void run(Scanner scanner){
        initialSetup(scanner);

        for(currentRound = 1; currentRound <= maxRounds; currentRound++){
            for (Trader agent : agents){
                currentPlayer = agent;
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": Turn Start");

                if (agent instanceof HumanAgent){
                    ((HumanAgent) agent).takeTurn(this, scanner);
                }
                else if(agent instanceof RandomAgent){
                    ((RandomAgent) agent).takeTurn(this, scanner);
                    System.out.println("Computer turn ended. Type 'go' to move to the next player.");
                    while (true) {
                        String wait = scanner.nextLine().trim();
                        if (wait.equalsIgnoreCase("go")) {
                            break;
                        }
                    }
                }
                updateLongestRoadOwner();
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": Turn End\n");
            }//end of each agent's turn

            /* Checking Victory Point status of each player */
            int winnerID = -1;
            System.out.println();
            System.out.println("Current Victory Points: ");
            for (Trader agent : agents){
                int agentVicPoints = ((Agent) agent).getVictoryPoints();
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": " + agentVicPoints);
                if (agentVicPoints >= 10){
                    winnerID = ((Agent) agent).getId();
                    currentRound = maxRounds + 1; //breaks the rounds loop
                    break; //gets out of for each loop
                }
            }//end of for each (check each player's vicpoints)

            if (winnerID != -1){
                System.out.println(currentRound + " / " + winnerID + ": Wins Game");
            }//end of if (win message)
            System.out.println();
        }//end of for loop (max round loop)
        endVisualizer();
    }//end of run()

    //Method for parsing the input, by using REGEX
    public boolean processCommand(String input) {
        if (input == null || input.isEmpty()) {
            return false; // ignore empty input
        }

        Agent player = (Agent) currentPlayer;

        // ---------- ROLL ----------
        if (input.matches("(?i)^\\s*roll\\s*$")) { // case-insensitive + optional spaces
            int roll = dice.roll();
            System.out.println(currentRound + " / " + player.getId() + ": Rolled a " + roll); //not calling printMessage, because of word 'Rolled a'

            if (roll != 7) {
                produceResource(roll);
            } else {
                robberPlay();
            }
            return true;
        }

        // ---------- LIST ----------
        if (input.matches("(?i)^\\s*list\\s*$")) {
            printMessage(player.getHandString());
            return true;
        }

        // ---------- BUILD ----------
        Pattern buildPattern = Pattern.compile("^\\s*build\\s+(road|settlement|city)\\s+(\\d+)(?:(\\s*,\\s*|\\s+)(\\d+))?\\s*$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = buildPattern.matcher(input);

        if (matcher.matches()) {
            String type = matcher.group(1);   // road, settlement, or city (original case)
            String first = matcher.group(2);
            String separator = matcher.group(3);
            String second = matcher.group(4);

            // call your existing handleBuild method
            boolean success = handleBuild(type, first, separator, second);

            // feedback messages for build success
            if (success) {
                if (type.equalsIgnoreCase("road")) {
                    printMessage("Built a road connecting node " + first + " and " + second);
                } else if (type.equalsIgnoreCase("settlement")) {
                    printMessage("Built a settlement on node " + first);
                } else if (type.equalsIgnoreCase("city")) {
                    printMessage("Upgraded settlement to city on node " + first);
                }
            }
            return success;
        }

    //The command didn't match anything
        printMessage("Invalid command.");
        return false;
    }

    public Trader[] getAgents() {
        return agents;
    }
    public void setCurrentPlayer(Trader player){
        currentPlayer = player;
    }

    //Method for calling the right build methods accordingly, depending on the input
    //Only being called by processCommand method above
    public boolean handleBuild(String type, String first, String separator, String second) {
        Agent player = (Agent) currentPlayer;

        if (type.equals("road")) {
            if (second == null) {
                printMessage("Road requires two node IDs.");
                return false;
            }

            if (separator == null || !separator.contains(",")) { //checks if a , is b/w the 2 node ids
                printMessage("Invalid format. Road requires a comma: build road node1, node2");
                return false;
            }

            int a = Integer.parseInt(first);
            int b = Integer.parseInt(second);
            Edge edge = board.getEdgeByIDNodes(a, b);

            if (edge == null || !canBuildRoad(edge)) {
                printMessage("Illegal road placement.");
                return false;
            }

            if (!player.canAfford(0)) {
                printMessage("Insufficient resources.");
                return false; //Stop here if they don't have enough cards
            }

            try{
                player.buildRoad(edge);
                updateLongestRoadOwner();
            }
            catch(Exception e){
                printMessage(e.getMessage());
                //System.out.println(e.getMessage());
                return false;
            }

            resourcePayement(0);
            updateBoard();
            return true;
        }

        if (type.equals("settlement")) {
            int id = Integer.parseInt(first);
            Node node = board.getIDNode(id);

            if (node == null || !canBuildSettlement(node)) {
                printMessage("Illegal settlement placement.");
                return false;
            }

            if (!player.canAfford(1)) {
                printMessage("Insufficient resources.");
                return false; //Stop here if they don't have enough cards
            }

            try{
                player.buildSettlement(node);
                recomputeLongestRoad();
            }
            catch(Exception e){
                printMessage(e.getMessage());
                //e.getMessage();
                return false;
            }

            resourcePayement(1);
            updateBoard();
            return true;
        }

        if (type.equals("city")) {
            int id = Integer.parseInt(first);
            Node node = board.getIDNode(id);

            if (node == null || !canBuildCity(node)) {
                printMessage("Illegal city placement.");
                return false;
            }
            if (!player.canAfford(2)) {
                printMessage("Insufficient resources.");
                return false; //Stop here if they don't have enough cards
            }

            try{
                player.buildCity(node);
            }
            catch(Exception e){
                printMessage(e.getMessage());
                //e.getMessage();
                return false;
            }

            resourcePayement(2);
            updateBoard();
            return true;
        }

        return false;
    }//end of handleBuild()

    //Helper method to print; it is public because Agent subclasses use this method too
    public void printMessage(String message){
        System.out.println(currentRound + " / " + ((Agent) currentPlayer).getId() + ": " + message);
    }

    //Distribute resources to agents with infrastructure on hexes matching the token
    private void produceResource(int token){
        HexTile[] producingTiles = board.getResourceProdTile(token); //getting the relevant hextiles

        for (HexTile currTile : producingTiles){
            if (currTile != null){

                Location[] tileNodes = currTile.getNodes(); //get nodes of that tile
                ResourceType resourceType = currTile.getResourceType();

                //Loop over each agent
                for (Trader agentTrader : agents){
                    Agent agent = (Agent) agentTrader;

                    //Loop over each infrastructure of the agent
                    for (int i=0; i < agent.getInfraCount(); i++){
                        Infrastructure infra = agent.getInfrastructure()[i]; //getting each infrastructure that the agent has currently

                        //Check if that infrastructure is on this tile
                        for (Location node : tileNodes){
                            if (infra.getLocation() == node){
                                int amount = (infra instanceof City) ? 2 : 1; //if city, then it produces 2*resource, otherwise it's a settlement which gives 1*resource
                        
                                //Give the agent the resource
                                for (int j=0; j<amount; j++){
                                    Card cardFromBank = bank.removeCard(resourceType); //remove the card from the bank
                                    if (cardFromBank != null){ //checking if the bank had at least one card to give to the agent
                                        agent.addCard(cardFromBank);
                                        System.out.println(currentRound + " / " + agent.getId() + ": Receives " + resourceType);
                                    } else {
                                        System.out.println(currentRound + " / " + agent.getId() + ": Bank is out of " + resourceType + " cards");
                                    }
                                }

                                break; //stop checking for other nodes for this infra
                            }
                        }
                    }
                }
            }
        }
    }//end of produceResource()

    private void resourcePayement(int toBuild) {//db - change name
        //Cast the currentPlayer to an Agent
        Agent player = (Agent) currentPlayer;

        //Since we know they can afford it, we perform the actual transaction
        //Define the recipes locally for the removal process
        ResourceType[][] materials = {
                {ResourceType.BRICK, ResourceType.LUMBER}, //Road
                {ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL}, //Settlement
                {ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE} //City
        };

        ResourceType[] recipe = materials[toBuild];

        //Remove cards from player and give to bank
        for (ResourceType type : recipe) {
            Card transitionCard = player.removeCard(type);
            if (transitionCard != null) {
                bank.addCard(transitionCard);
            }
        }
    }

    public List<Edge> getLegalRoadMoves(Agent agent) {
        List<Edge> legalEdges = new ArrayList<>();
        //Save state to ensure we don't accidentally skip a human's turn
        Trader original = this.currentPlayer;
        this.currentPlayer = agent;

        for (Edge e : board.getAllEdges()) {
            if (e != null && this.canBuildRoad(e)) {
                legalEdges.add(e);
            }
        }

        this.currentPlayer = original; //Restore original turn state
        return legalEdges;
    }

    public List<Node> getLegalSettlementMoves(Agent agent) {
        List<Node> legalNodes = new ArrayList<>();
        //Save state to ensure we don't accidentally skip a human's turn
        Trader original = this.currentPlayer;
        this.currentPlayer = agent;

        for (Node n : board.getAllNodes()) {
            if (n != null && this.canBuildSettlement(n)) {
                legalNodes.add(n);
            }
        }

        this.currentPlayer = original; //Restore original turn state
        return legalNodes;
    }

    public List<Node> getLegalCityMoves(Agent agent) {
        List<Node> legalNodes = new ArrayList<>();
        //Save state to ensure we don't accidentally skip a human's turn
        Trader originalPlayer = this.currentPlayer;
        this.currentPlayer = agent;

        for (Node n : board.getAllNodes()) {
            if (n != null && this.canBuildCity(n)) {
                legalNodes.add(n);
            }
        }

        this.currentPlayer = originalPlayer; //Restore original turn state
        return legalNodes;
    }

    private Location roadEdgeInput(Scanner s) {
        Edge edge = null;

        while (edge == null) {
            //Prompt for the first node before reading, to make it easy to understand what is happening
            System.out.print(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Enter start node ID: ");
            String aStr = s.nextLine();
            int a = Integer.parseInt(aStr.trim());

            //Prompt for the second node before reading, for the same reason as above
            System.out.print(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Enter end node ID: ");
            String bStr = s.nextLine();
            int b = Integer.parseInt(bStr.trim());

            //Attempt to find the edge
            edge = board.getEdgeByIDNodes(a, b);

            if (edge == null) {
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid node IDs (No edge exists between #" + a + " and #" + b + "). Try Again");
            } else {
                //Confirm the selection once valid
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects edge (#" + a + ", #" + b + ")");
            }
        }
        return edge;
    }

    private Location buildingNodeInput(Scanner s) {
        Node node = null;
        while (node == null) {
            //Prompt before reading input, to make it easy to understand what is happening
            System.out.print(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Enter node ID: ");

            String idStr = s.nextLine();
            int id = Integer.parseInt(idStr.trim());

            node = board.getIDNode(id);

            if (node == null) {
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid node ID. Try Again");
            }
        }
        //Final confirmation message
        System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects node (#" + node.getId() + ")");
        return node;
    }

    private boolean canBuildRoad(Edge edge){
        Agent player = (Agent) currentPlayer; //type casting to use Agent methods, not just Trader
        if (edge.isOccupied()) return false;

        int a = edge.getStart();
        int b = edge.getEnd();

        //Check player's infrastructure
        for (int i = 0; i < player.getInfraCount(); i++) {
            Infrastructure infra = player.getInfrastructure()[i];
            Location loc = infra.getLocation();

            //Connected to player's settlement/city
            if (loc instanceof Node){
                Node n = (Node) loc;
                if (n.getId() == a || n.getId() == b) return true;
            }

            //Connected to player's road
            if (loc instanceof Edge) {
                Edge e = (Edge) loc;
                boolean isConnected = (e.getStart() == a || e.getStart() == b || e.getEnd() == a   || e.getEnd() == b);
                if (isConnected){
                    //finds the shared node ID
                    int sharedNode;
                    if (e.getStart() == a || e.getEnd() == a) sharedNode = a;
                    else sharedNode = b;

                    //If shared node is occupied by ANOTHER player - build should fail
                    for (Trader players : agents){
                        Agent enemyPlayer = (Agent) players;
                        if (enemyPlayer == player) continue; //no need to check if the node is the currplayer's or not

                        for (int j = 0; j < enemyPlayer.getInfraCount(); j++){
                            Infrastructure otherInfra = enemyPlayer.getInfrastructure()[j];

                            if (otherInfra instanceof Settlement || otherInfra instanceof City){
                                Node otherNode = (Node) otherInfra.getLocation();
                                if (otherNode.getId() == sharedNode){
                                    return false; //build has been blocked by enemy building
                                }
                            }
                        }//end of for loop
                    }
                    return true;
                }
            }
        }//end of for loop (checking player's infrastructures)
        return false;
    }//end of canBuildRoad

    private boolean canBuildSettlement(Node node){ //Ch
        Agent player = (Agent) currentPlayer;
        if (node.isOccupied()) return false;

        int nodeId = node.getId();

        //must connect to player's existing road
        boolean connectedToRoad = false;

        for (int i = 0; i < player.getInfraCount(); i++) {
            Infrastructure infra = player.getInfrastructure()[i];

            if (infra instanceof Road){
                Edge e = (Edge) infra.getLocation();

                if (e.getStart() == nodeId || e.getEnd() == nodeId) {
                    connectedToRoad = true;
                    break;
                }
            }
        }//end of for loop (checking player's infrastructures)

        if (!connectedToRoad) return false;

        if (!noAdjacentSettlements(node)) return false;

        return true;
    }//end of canBuildSettlement()

    private boolean canBuildCity(Node node){
        Agent player = (Agent) currentPlayer;
        for (int i = 0; i < player.getInfraCount(); i++){
            Infrastructure infra = player.getInfrastructure()[i];
            //Checking if the infra. is a settlement and has the same location as where the player wants to place City
            if (infra instanceof Settlement && infra.getLocation() == node) return true;
        }//end of for loop (checking player's infrastructures)
        return false;
    }//end of canBuildCity()

    private void giveResourceInitialSetup(Node node, Trader currentPlayer){
        Agent player = (Agent) currentPlayer;
        
        for (HexTile tile : board.getTiles()){
            Location[] tileNodes = tile.getNodes();

            for (Location tileNode : tileNodes){
                if (tileNode == node){
                    ResourceType type = tile.getResourceType();
                    if(type != ResourceType.DESERT){
                        Card card = bank.removeCard(type);

                        if(card != null){
                            System.out.println(currentRound + " / " + player.getId() + ": Receives " + type);
                            player.addCard(card);
                        }
                    }
                    break;
                }
            }
        }
    }

    private void initialSetup(Scanner scanner){
        //Forward order
        for (Trader agent : agents){
            executeSetupTurn(agent, scanner, "Initial");
            System.out.println();
        }//end of forward turn order of players
        //Reverse Order
        for (int i = agents.length - 1; i >= 0; i--){
            executeSetupTurn(agents[i], scanner, "Secondary");
            System.out.println();
        }//end of backwards turn order of players
    }//end of initialSetup()

    //Created this helper method for initialSetup method, to avoid duplicate code for forward and reverse order
    private void executeSetupTurn(Trader agent, Scanner scanner, String phase) {
        currentPlayer = agent;
        Agent a = (Agent) agent;
        System.out.println(currentRound + " / " + a.getId() + ": Selecting " + phase + " Settlement and Road");

        Node settlementSpot = null;
        Edge roadSpot = null;

        if (a instanceof HumanAgent) {
            settlementSpot = setupSettlementInput(scanner);
            roadSpot = setupRoadInput(scanner, settlementSpot);
        } else if (agent instanceof RandomAgent) {
            settlementSpot = findRandomValidSettlement();
            roadSpot = findRandomValidRoad(settlementSpot);

            //Adding these lines for visibility:
            System.out.println(currentRound + " / " + a.getId() + ": Computer selects node (#" + settlementSpot.getId() + ")");
            System.out.println(currentRound + " / " + a.getId() + ": Computer selects edge (#" + roadSpot.getStart() + ", #" + roadSpot.getEnd() + ")");
            System.out.println("Computer turn ended. Type 'go' to move to the next player.");
            while (true) {
                String wait = scanner.nextLine().trim();
                if (wait.equalsIgnoreCase("go")) {
                    break;
                }
            }
        }

        a.buildSettlement(settlementSpot);
        a.buildRoad(roadSpot);
        System.out.println(currentRound + " / " + a.getId() + ": Placed " + phase + " Infrastructure");
        updateBoard();

        if (phase.equals("Secondary") && settlementSpot != null) {
            giveResourceInitialSetup(settlementSpot, agent);
        }
    }

    private Node findRandomValidSettlement() {
        List<Node> validNodes = new ArrayList<>();
        // We get all nodes, so we are iterating 0 to 53
        for (int i = 0; i < 54; i++) {
            Node n = board.getIDNode(i);
            if (n != null && !n.isOccupied() && noAdjacentSettlements(n)) {
                validNodes.add(n);
            }
        }
        // Pick one randomly from all valid nodes that we have added
        return validNodes.get(random.nextInt(validNodes.size()));
    }

    private Edge findRandomValidRoad(Node settlement) {
        List<Edge> validEdges = new ArrayList<>();
        int nodeId = settlement.getId();

        // Check all edges in the MapSkeleton
        for (int[] e : MapSkeleton.edges) {
            if (e[0] == nodeId || e[1] == nodeId) {
                Edge edge = board.getEdgeByIDNodes(e[0], e[1]);
                if (edge != null && !edge.isOccupied()) {
                    validEdges.add(edge);
                }
            }
        }
        // Pick one randomly from all valid edges that we have added
        return validEdges.get(random.nextInt(validEdges.size()));
    }

    private Node setupSettlementInput(Scanner scanner){
        while (true){
            Node node = (Node) buildingNodeInput(scanner);
            if (node.isOccupied() || !noAdjacentSettlements(node)){
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                continue; //Get user input again
            }

            return node;
        }
    }//end of setupSettlementInput

    private Edge setupRoadInput(Scanner scanner, Node settlement){
        while (true){
            Edge edge = (Edge) roadEdgeInput(scanner);
            if (edge.isOccupied()){
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                continue;
            }
            int a = edge.getStart();
            int b = edge.getEnd();

            if (a == settlement.getId() || b == settlement.getId()){
                return edge;
            }
            System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
        }
    }//end of setupRoadInput()

    private boolean noAdjacentSettlements(Node node){
        int nodeId = node.getId();

        for (int[] e : MapSkeleton.edges){
            if (e[0] == nodeId || e[1] == nodeId){

                int neighborId;
                if (e[0] == nodeId) neighborId = e[1];
                else neighborId = e[0];

                Node neighbor = board.getIDNode(neighborId);
                if (neighbor.isOccupied()) return false;
            }
        }
        return true;
    }//end of noAdjacentSettlements()

    private void robberPlay(){
        Robber robber = board.getRobber();

        //Discard Phase
        for (Trader agent : agents){
            Agent player = (Agent) agent;
            int agentCardCount = player.getTotalCardCount();
            if (agentCardCount > 7){
                List<Card> discardCards = player.discardHalfOfHand(random);
                for (Card discardCard : discardCards)
                    bank.addCard(discardCard);

                if (!discardCards.isEmpty()){
                    //printMessage(": discard half their deck");
                    System.out.println(currentRound + " / " + player.getId() + ": Discard half their deck");
                }
            }
        }
        //Robber Move Phase
        List<HexTile> tiles = board.getTiles();
        HexTile targetTile;
        do {
            int randomTileID = random.nextInt(tiles.size());
            targetTile = tiles.get(randomTileID);
        } while (!robber.moveRobber(targetTile)); //the loops runs again if the random id was the same as the old location of the robber

        //System.out.println(currentRound + " / " + ((Agent) currentPlayer).getId() + ": moved the robber to tile " + targetTile.getlandTileID());
        writer.moveRobber(targetTile.getlandTileID());
        printMessage("Moved the robber to tile " + targetTile.getlandTileID());

        //Steal Phase
        Location[] tileNodes = targetTile.getNodes();
        //List<Agent> qualifyingAgents = new ArrayList<>();
        Set<Agent> qualifyingAgents = new HashSet<>(); //Prevents duplicate victims

        //find all qualifying players (adjacent to robber tile)
        for (Trader agent : agents){
            if (agent != currentPlayer && agent instanceof Agent enemyAgent){ //type-casting
                boolean found = false;
                //Loop over each infrastructure of the agent
                for (int i = 0; i < enemyAgent.getInfraCount() && !found; i++) {
                    Infrastructure infra = enemyAgent.getInfrastructure()[i];
                    //Check if that infrastructure is on this tile
                    for (Location node : tileNodes){
                        if (infra.getLocation() == node){
                            qualifyingAgents.add(enemyAgent); //agent added to qualifyingAgents to be robbed blind
                            found = true;
                            break;
                        }
                    }//end of for
                }//end of for
            }//end of if
        }//end of for

        if (!qualifyingAgents.isEmpty()) {
            List<Agent> victimList = new ArrayList<>(qualifyingAgents); //changes it to an arraylist from a hashset

            int randomQualifyingAgent = random.nextInt(victimList.size()); //number between [0 - size of the num of qualifying agents]

            Agent victim = victimList.get(randomQualifyingAgent);
            //steal random card from victim
            Card stolenCard = victim.removeRandomCard(random);
            if (stolenCard != null){
                currentPlayer.addCard(stolenCard);
                printMessage("Steals a card from " + victim.getId());
                //System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": steals a card from" + victim.getId());
            }
            else {
                printMessage(victim.getId() + " Has no cards to steal");
                //System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + victim.getId() + " has no cards to steal");
            }
        }//end of if
    }//end of robberPlay()

    private void updateBoard(){
        writer.write(this);
    }

    private void launchVisualizer(){
        try{
            //ProcessBuilder processBuilder = new ProcessBuilder("python", "visualizer/light_visualizer.py", "visualizer/base_map.json", "--watch");
            //ProcessBuilder processBuilder = new ProcessBuilder(".venv\\Scripts\\python.exe", "light_visualizer.py",  "base_map.json", "--watch");
            ProcessBuilder processBuilder = new ProcessBuilder(
                    "visualizer\\.venv\\Scripts\\python.exe",
                    "visualizer\\light_visualizer.py",
                    "visualizer\\base_map.json",
                    "--watch"
            );
            processBuilder.redirectErrorStream(true);
            processBuilder.inheritIO();
            visualizer = processBuilder.start();
            writer.write(this);//initialize with an empty game board
        }
        catch(IOException e){
            System.err.println(e.getMessage());
        }

    }

    public void endVisualizer(){
        writer.setBaseMap(); //restore base map to original state for next game
        visualizer.destroy();
    }

    public Board getBoard(){//UML
        return board;
    }

    public boolean isBlocked(int nodeId, Agent agent){//UML
        for (Trader t : getAgents()){
            if (!(t instanceof Agent other)) continue;
            if (other == agent) continue; //comparing object identity, not inside value

            for (int i = 0; i < other.getInfraCount(); i++){
                Infrastructure infra = other.getInfrastructure()[i];

                if (infra instanceof Settlement || infra instanceof City){
                    Node n = (Node) infra.getLocation();

                    if (n.getId() == nodeId){
                        return true;
                    }
                }
            }
        }
        return false;
    }//end of isBlocked()

    public void updateLongestRoadOwner(){//UML
        Agent a = (Agent) currentPlayer;
        int length = a.getLongestRoadLength(this);

        //player beats the current record
        if (length >= minForLongestRoad && length > currentLongestRoadLen){
            setNewLongestRoadOwner(a, length);
        }
    }
    private void recomputeLongestRoad() {//UML
        Agent bestAgent = null;
        int bestLength = 0;

        for (Trader t : agents) {
            Agent a = (Agent) t;
            int length = a.getLongestRoadLength(this);

            if (length >= minForLongestRoad && length > bestLength){
                bestLength = length;
                bestAgent = a;
            }
        }
        if (bestAgent != null){
            setNewLongestRoadOwner(bestAgent, bestLength);
        }
        else{
            if (currentLongestRoadOwner != null) {
                System.out.println(currentRound + " / " + currentLongestRoadOwner.getId() + ": no longer holds the Longest Road");
            }
            currentLongestRoadOwner = null;
            currentLongestRoadLen = 0;
        }
    }
    private void setNewLongestRoadOwner(Agent newOwner, int newLength){//UML
        currentLongestRoadOwner = newOwner;
        currentLongestRoadLen = newLength;

        for (Trader t : agents) {
            Agent a = (Agent) t;
            a.setHasLongestRoad(a == newOwner);
        }

        if (newOwner != null) {
            System.out.println(currentRound + " / " + newOwner.getId() + ": claimed Longest Road at length " + currentLongestRoadLen);
        }
    }
}//end of Game() class