// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.io.IOException;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class GameManager{
    private int maxRounds;
    private int currentRound;
    private Board board;
    private Trader[] agents;
    private Trader bank;

    private Dice dice;

    private Random random;

    private Trader currentPlayer;
    private JsonWriter writer;
    private Process visualizer;

    // Field addition for undo/redo mechanism
    private CommandManager commandManager = new CommandManager();
    private int minForLongestRoad = 5;//UML
    private Agent currentLongestRoadOwner;//UML
    private int currentLongestRoadLen;//UML

    @SuppressWarnings("java:S2245") // Pseudorandom RNG okay for game logic
    public GameManager(int rounds, int numPlayers, boolean demoMode){
        this.maxRounds = rounds;
        agents = new Agent[numPlayers];

        agents[0] = new HumanAgent(1); //first player is human

        if (demoMode) this.random = new Random(12);

        else this.random = new Random();

        dice = new MultiDice(2, random);

        for (int i = 1; i < numPlayers; i++){
            if (demoMode){
                agents[i] = new RandomAgent(i + 1, new Random((long) i + 20)); //the other players are computers
            }
            else{
                agents[i] = new RandomAgent(i + 1, new Random()); //the other players are computers
            }
        }
        board = new Board();
        bank = new Bank();

        currentLongestRoadOwner = null;
        currentLongestRoadLen = 0;

        writer = new JsonWriter("state.json", "visualizer/base_map.json");
        launchVisualizer();
    }//end of Game constructor

    public void run(Scanner scanner){
        initialSetup(scanner);

        for(currentRound = 1; currentRound <= maxRounds; currentRound++){
            for (Trader agent : agents){
                currentPlayer = agent;
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": Turn Start");

                if (agent instanceof HumanAgent){
                    ((HumanAgent) agent).takeTurn(this, scanner);
                }
                else if(agent instanceof RandomAgent){
                    ((RandomAgent) agent).takeTurn(this, scanner);
                    System.out.println("Computer turn ended. Type 'go' to move to the next player.");
                    while (true) {
                        String wait = scanner.nextLine().trim();
                        if (wait.equalsIgnoreCase("go")) {
                            break;
                        }
                    }
                }
                updateLongestRoadOwner();
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": Turn End\n");
            }//end of each agent's turn

            /* Checking Victory Point status of each player */
            int winnerID = -1;
            System.out.println();
            System.out.println("Current Victory Points: ");
            for (Trader agent : agents){
                int agentVicPoints = ((Agent) agent).getVictoryPoints();
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": " + agentVicPoints);
                if (agentVicPoints >= 10){
                    winnerID = ((Agent) agent).getId();
                    currentRound = maxRounds + 1; //breaks the rounds loop
                    break; //gets out of for each loop
                }
            }//end of for each (check each player's vicpoints)

            if (winnerID != -1){
                System.out.println(currentRound + " / " + winnerID + ": Wins Game");
            }//end of if (win message)
            System.out.println();
        }//end of for loop (max round loop)
        endVisualizer();
    }//end of run()

    //Method for parsing the input, by using REGEX
    public boolean processCommand(String input) {
        if (input == null || input.isEmpty()) {
            return false; // ignore empty input
        }

        Agent player = (Agent) currentPlayer;

        // ---------- ROLL ----------
        if (input.matches("(?i)^\\s*roll\\s*$")) { // case-insensitive + optional spaces
            int roll = dice.roll();
            System.out.println(currentRound + " / " + player.getId() + ": Rolled a " + roll); //not calling printMessage, because of word 'Rolled a'

            if (roll != 7) {
                produceResource(roll);
            } else {
                robberPlay();
            }
            return true;
        }

        // ---------- LIST ----------
        if (input.matches("(?i)^\\s*list\\s*$")) {
            printMessage(player.getHandString());
            return true;
        }

        // ---------- BUILD ----------
        Pattern buildPattern = Pattern.compile("^\\s*build\\s+(road|settlement|city)\\s+(\\d+)(?:(\\s*,\\s*|\\s+)(\\d+))?\\s*$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = buildPattern.matcher(input);

        if (matcher.matches()) {
            String type = matcher.group(1);   // road, settlement, or city (original case)
            String first = matcher.group(2);
            String separator = matcher.group(3);
            String second = matcher.group(4);

            // call your existing handleBuild method
            boolean success = handleBuild(type, first, separator, second);

            // feedback messages for build success
            if (success) {
                if (type.equalsIgnoreCase("road")) {
                    printMessage("Built a road connecting node " + first + " and " + second);
                } else if (type.equalsIgnoreCase("settlement")) {
                    printMessage("Built a settlement on node " + first);
                } else if (type.equalsIgnoreCase("city")) {
                    printMessage("Upgraded settlement to city on node " + first);
                }
            }
            return success;
        }

        //The command didn't match anything
        printMessage("Invalid command.");
        return false;
    }

    public Trader[] getAgents() {
        return agents;
    }

    //Method for calling the right build methods accordingly, depending on the input
    //Only being called by processCommand method above
    public boolean handleBuild(String type, String first, String separator, String second) {
        Agent player = (Agent) currentPlayer;

        if (type.equals("road")) {
            if (second == null) {
                printMessage("Road requires two node IDs.");
                return false;
            }

            if (separator == null || !separator.contains(",")) { //checks if a , is b/w the 2 node ids
                printMessage("Invalid format. Road requires a comma: build road node1, node2");
                return false;
            }

            int a = Integer.parseInt(first);
            int b = Integer.parseInt(second);
            Edge edge = board.getEdgeByIDNodes(a, b);

            if (edge == null || !board.canBuildRoad(edge, player, agents)) {
                printMessage("Illegal road placement.");
                return false;
            }

            if (!player.canAfford(0)) {
                printMessage("Insufficient resources.");
                return false; //Stop here if they don't have enough cards
            }

            try{
                // Update for undo/redo mechanism
                commandManager.executeCommand(new BuildRoadCommand(this, bank, player, edge));
                updateLongestRoadOwner();
            }
            catch(Exception e){
                printMessage(e.getMessage());
                //System.out.println(e.getMessage());
                return false;
            }

            updateBoard();
            return true;
        }

        if (type.equals("settlement")) {
            int id = Integer.parseInt(first);
            Node node = board.getIDNode(id);

            if (node == null || !board.canBuildSettlement(node, player)) {
                printMessage("Illegal settlement placement.");
                return false;
            }

            if (!player.canAfford(1)) {
                printMessage("Insufficient resources.");
                return false; //Stop here if they don't have enough cards
            }

            try{

                // Update for undo/redo mechanism
                commandManager.executeCommand(new BuildSettlementCommand(this, bank, player, node));
                recomputeLongestRoad();
            }
            catch(Exception e){
                printMessage(e.getMessage());
                //e.getMessage();
                return false;
            }

            updateBoard();
            return true;
        }

        if (type.equals("city")) {
            int id = Integer.parseInt(first);
            Node node = board.getIDNode(id);

            if (node == null || !board.canBuildCity(node, player)) {
                printMessage("Illegal city placement.");
                return false;
            }
            if (!player.canAfford(2)) {
                printMessage("Insufficient resources.");
                return false; //Stop here if they don't have enough cards
            }

            try{
                // Update for undo/redo mechanism
                commandManager.executeCommand(new BuildCityCommand(this, bank, player, node));
            }
            catch(Exception e){
                printMessage(e.getMessage());
                //e.getMessage();
                return false;
            }

            updateBoard();
            return true;
        }

        return false;
    }//end of handleBuild()

    //Helper method to print; it is public because Agent subclasses use this method too
    public void printMessage(String message){
        System.out.println(currentRound + " / " + ((Agent) currentPlayer).getId() + ": " + message);
    }

    //Distribute resources to agents with infrastructure on hexes matching the token
    private void produceResource(int token){
        HexTile[] producingTiles = board.getResourceProdTile(token); //getting the relevant hextiles

        for (HexTile currTile : producingTiles){
            if (currTile != null){

                Location[] tileNodes = currTile.getNodes(); //get nodes of that tile
                ResourceType resourceType = currTile.getResourceType();

                //Loop over each agent
                for (Trader agentTrader : agents){
                    Agent agent = (Agent) agentTrader;

                    //Loop over each infrastructure of the agent
                    for (int i=0; i < agent.getInfraCount(); i++){
                        Infrastructure infra = agent.getInfrastructure()[i]; //getting each infrastructure that the agent has currently

                        //Check if that infrastructure is on this tile
                        for (Location node : tileNodes){
                            if (infra.getLocation() == node){
                                int amount = (infra instanceof City) ? 2 : 1; //if city, then it produces 2*resource, otherwise it's a settlement which gives 1*resource

                                //Give the agent the resource
                                for (int j=0; j<amount; j++){
                                    Card cardFromBank = bank.removeCard(resourceType); //remove the card from the bank
                                    if (cardFromBank != null){ //checking if the bank had at least one card to give to the agent
                                        agent.addCard(cardFromBank);
                                        System.out.println(currentRound + " / " + agent.getId() + ": Receives " + resourceType);
                                    } else {
                                        System.out.println(currentRound + " / " + agent.getId() + ": Bank is out of " + resourceType + " cards");
                                    }
                                }

                                break; //stop checking for other nodes for this infra
                            }
                        }
                    }
                }
            }
        }
    }//end of produceResource()



    public List<Edge> getLegalRoadMoves(Agent agent) {
        return board.getLegalRoadMoves(agent, agents);
    }

    public List<Node> getLegalSettlementMoves(Agent agent) {
        return board.getLegalSettlementMoves(agent);
    }

    public List<Node> getLegalCityMoves(Agent agent) {
        return board.getLegalCityMoves(agent);
    }

    private Location roadEdgeInput(Scanner s) {
        Edge edge = null;

        while (edge == null) {
            //Prompt for the first node before reading, to make it easy to understand what is happening
            System.out.print(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Enter start node ID: ");
            String aStr = s.nextLine();
            int a = Integer.parseInt(aStr.trim());

            //Prompt for the second node before reading, for the same reason as above
            System.out.print(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Enter end node ID: ");
            String bStr = s.nextLine();
            int b = Integer.parseInt(bStr.trim());

            //Attempt to find the edge
            edge = board.getEdgeByIDNodes(a, b);

            if (edge == null) {
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid node IDs (No edge exists between #" + a + " and #" + b + "). Try Again");
            } else {
                //Confirm the selection once valid
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects edge (#" + a + ", #" + b + ")");
            }
        }
        return edge;
    }

    private Location buildingNodeInput(Scanner s) {
        Node node = null;
        while (node == null) {
            //Prompt before reading input, to make it easy to understand what is happening
            System.out.print(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Enter node ID: ");

            String idStr = s.nextLine();
            int id = Integer.parseInt(idStr.trim());

            node = board.getIDNode(id);

            if (node == null) {
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid node ID. Try Again");
            }
        }
        //Final confirmation message
        System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects node (#" + node.getId() + ")");
        return node;
    }

    // canBuildRoad() moved to Board

    // canBuildSettlement() moved to Board

    // canBuildCity() moved to Board

    private void giveResourceInitialSetup(Node node, Trader currentPlayer){
        Agent player = (Agent) currentPlayer;

        for (HexTile tile : board.getTiles()){
            Location[] tileNodes = tile.getNodes();

            for (Location tileNode : tileNodes){
                if (tileNode == node){
                    ResourceType type = tile.getResourceType();
                    if(type != ResourceType.DESERT){
                        Card card = bank.removeCard(type);

                        if(card != null){
                            System.out.println(currentRound + " / " + player.getId() + ": Receives " + type);
                            player.addCard(card);
                        }
                    }
                    break;
                }
            }
        }
    }

    private void initialSetup(Scanner scanner){
        //Forward order
        for (Trader agent : agents){
            executeSetupTurn(agent, scanner, "Initial");
            System.out.println();
        }//end of forward turn order of players
        //Reverse Order
        for (int i = agents.length - 1; i >= 0; i--){
            executeSetupTurn(agents[i], scanner, "Secondary");
            System.out.println();
        }//end of backwards turn order of players
    }//end of initialSetup()

    //Created this helper method for initialSetup method, to avoid duplicate code for forward and reverse order
    private void executeSetupTurn(Trader agent, Scanner scanner, String phase) {
        currentPlayer = agent;
        Agent a = (Agent) agent;
        System.out.println(currentRound + " / " + a.getId() + ": Selecting " + phase + " Settlement and Road");

        Node settlementSpot = null;
        Edge roadSpot = null;

        if (a instanceof HumanAgent) {
            settlementSpot = setupSettlementInput(scanner);
            roadSpot = setupRoadInput(scanner, settlementSpot);
        } else if (agent instanceof RandomAgent) {
            settlementSpot = findRandomValidSettlement();
            roadSpot = findRandomValidRoad(settlementSpot);

            //Adding these lines for visibility:
            System.out.println(currentRound + " / " + a.getId() + ": Computer selects node (#" + settlementSpot.getId() + ")");
            System.out.println(currentRound + " / " + a.getId() + ": Computer selects edge (#" + roadSpot.getStart() + ", #" + roadSpot.getEnd() + ")");
            System.out.println("Computer turn ended. Type 'go' to move to the next player.");
            while (true) {
                String wait = scanner.nextLine().trim();
                if (wait.equalsIgnoreCase("go")) {
                    break;
                }
            }
        }

        a.buildSettlement(settlementSpot);
        a.buildRoad(roadSpot);
        System.out.println(currentRound + " / " + a.getId() + ": Placed " + phase + " Infrastructure");
        updateBoard();

        if (phase.equals("Secondary") && settlementSpot != null) {
            giveResourceInitialSetup(settlementSpot, agent);
        }
    }

    private Node findRandomValidSettlement() {
        List<Node> validNodes = new ArrayList<>();
        // We get all nodes, so we are iterating 0 to 53
        for (int i = 0; i < 54; i++) {
            Node n = board.getIDNode(i);
            if (n != null && !n.isOccupied() && board.noAdjacentSettlements(n)) {
                validNodes.add(n);
            }
        }
        // Pick one randomly from all valid nodes that we have added
        return validNodes.get(random.nextInt(validNodes.size()));
    }

    private Edge findRandomValidRoad(Node settlement) {
        List<Edge> validEdges = new ArrayList<>();
        int nodeId = settlement.getId();

        // Check all edges in the MapSkeleton
        for (int[] e : MapSkeleton.edges) {
            if (e[0] == nodeId || e[1] == nodeId) {
                Edge edge = board.getEdgeByIDNodes(e[0], e[1]);
                if (edge != null && !edge.isOccupied()) {
                    validEdges.add(edge);
                }
            }
        }
        // Pick one randomly from all valid edges that we have added
        return validEdges.get(random.nextInt(validEdges.size()));
    }

    private Node setupSettlementInput(Scanner scanner){
        while (true){
            Node node = (Node) buildingNodeInput(scanner);
            if (node.isOccupied() || !board.noAdjacentSettlements(node)){
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                continue; //Get user input again
            }

            return node;
        }
    }//end of setupSettlementInput

    private Edge setupRoadInput(Scanner scanner, Node settlement){
        while (true){
            Edge edge = (Edge) roadEdgeInput(scanner);
            if (edge.isOccupied()){
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                continue;
            }
            int a = edge.getStart();
            int b = edge.getEnd();

            if (a == settlement.getId() || b == settlement.getId()){
                return edge;
            }
            System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
        }
    }//end of setupRoadInput()

    // noAdjacentSettlements() moved to Board

    private void robberPlay() {
        // Robber logic delegated to Robber.activate() — discard, move, and steal
        // are all self-contained within the Robber class
        board.getRobber().activate(agents, currentPlayer, bank, board.getTiles(), random, currentRound, writer);
    }//end of robberPlay()

    // Making this method public so undo/redo mechanism works
    public void updateBoard(){
        writer.write(agents);
    }

    private void launchVisualizer(){
        try{
            //ProcessBuilder processBuilder = new ProcessBuilder("python", "visualizer/light_visualizer.py", "visualizer/base_map.json", "--watch");
            //ProcessBuilder processBuilder = new ProcessBuilder(".venv\\Scripts\\python.exe", "light_visualizer.py",  "base_map.json", "--watch");
            ProcessBuilder processBuilder = new ProcessBuilder(
                    "visualizer\\.venv\\Scripts\\python.exe",
                    "visualizer\\light_visualizer.py",
                    "visualizer\\base_map.json",
                    "--watch"
            );
            processBuilder.redirectErrorStream(true);
            processBuilder.inheritIO();
            visualizer = processBuilder.start();
            updateBoard();//initialize with an empty game board
        }
        catch(IOException e){
            System.err.println(e.getMessage());
        }

    }

    public void endVisualizer(){
        writer.setBaseMap(); //restore base map to original state for next game
        visualizer.destroy();
    }

    // Method additions for undo/redo mechanism
    public CommandManager getCommandManager() {
        return commandManager;
    }

    public Trader getBank() {
        return bank;
    }

    public Board getBoard() {
        return board;
    }

    public boolean isBlocked(int nodeId, Agent agent) {
        return board.isBlocked(nodeId, agent, agents);
    }

    public void updateLongestRoadOwner(){//UML
        Agent a = (Agent) currentPlayer;
        int length = a.getLongestRoadLength(this);

        //player beats the current record
        if (length >= minForLongestRoad && length > currentLongestRoadLen){
            setNewLongestRoadOwner(a, length);
        }
    }
    private void recomputeLongestRoad() {//UML
        Agent bestAgent = null;
        int bestLength = 0;

        for (Trader t : agents) {
            Agent a = (Agent) t;
            int length = a.getLongestRoadLength(this);

            if (length >= minForLongestRoad && length > bestLength){
                bestLength = length;
                bestAgent = a;
            }
        }
        if (bestAgent != null){
            setNewLongestRoadOwner(bestAgent, bestLength);
        }
        else{
            if (currentLongestRoadOwner != null) {
                System.out.println(currentRound + " / " + currentLongestRoadOwner.getId() + ": no longer holds the Longest Road");
            }
            currentLongestRoadOwner = null;
            currentLongestRoadLen = 0;
        }
    }
    private void setNewLongestRoadOwner(Agent newOwner, int newLength){//UML
        currentLongestRoadOwner = newOwner;
        currentLongestRoadLen = newLength;

        for (Trader t : agents) {
            Agent a = (Agent) t;
            a.setHasLongestRoad(a == newOwner);
        }

        if (newOwner != null) {
            System.out.println(currentRound + " / " + newOwner.getId() + ": claimed Longest Road at length " + currentLongestRoadLen);
        }
    }

    public void setCurrentPlayer(Trader currentPlayer){
        this.currentPlayer = currentPlayer;
    }
}//end of GameManager class