// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/**
 * A class to define the attributes and behaviours of a location that can be built by a player.
 */

public abstract class Location{
	private boolean occupied;

    public Location(){
        this.occupied = false;
    }

	public boolean isOccupied(){
        return occupied;
	}

	public void setOccupied(){
        this.occupied = true;
	}

    // The following method is added so the undo/redo mechanism works and respects the encapsulation principle
    public void clearOccupied() {
        this.occupied = false;
    }

}//end of Location() class
