// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/

import org.json.JSONObject;

/**
 * A type of infrastructure, built on edges of tiles.
 */
public class Road extends Infrastructure {
	public Road(Agent owner){
		super(0, owner); //Road gives 0 VP
	}

	@Override
    public void build(Location location) {
        if (location instanceof Node){
            throw new IllegalStateException("This is an invalid location for the road.");
        }
		
		if(location.isOccupied()){
            throw new IllegalStateException("This location is already occupied by another road.");
        }

        super.setLocation(location);
		location.setOccupied(); //only when there is nothing at that location
    }

    @Override
    public String getInfraName(){
        return "ROAD";
    }

    @Override
    public JSONObject toJSON() {
        // "a" : start, "b": end, "owner": colour
        JSONObject roadObj = new JSONObject();
        int start, end;
        if (this.getLocation() instanceof Edge){
            start = ((Edge) this.getLocation()).getStart();
            end = (((Edge) this.getLocation()).getEnd());
        }
        else {
            return null;
        }
        roadObj.put("a", start);
        roadObj.put("b", end);
        roadObj.put("owner", this.getOwner().getColourName());

        return roadObj;
    }
}
