// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/**
 * This class represents the abstract entity of a trader, which holds resources, and can trade them.
 */
public abstract class Trader{
	private int[] resourceCount;
    private List<Card> resourceHand;
    //private Card[] resourceHand;

    public Trader(){
        resourceHand = new ArrayList<>();
        resourceCount = new int[5];
        Arrays.fill(resourceCount, 0);
    }

	/**
	 * 
	 * @param newCard - the card being added to the hand
	 */
	public void addCard(Card newCard){
        resourceHand.add(newCard);
        resourceCount[getTypeFromCard(newCard).getIndex()]++;
	}//end of addCard

	/**
	 * 
	 * @return c - the card that was removed so it can be traded
	 */
	public Card removeCard(ResourceType type){

        if (type == ResourceType.DESERT) return null;

        for (int i = 0; i < resourceHand.size(); i++) {
            Card c = resourceHand.get(i);
            ResourceType resourceType = ResourceType.valueOf(c.getCardType()); //remove
            if (getTypeFromCard(c) == type){
                resourceHand.remove(i);
                resourceCount[type.getIndex()]--;
                return c;
            }//end of if
        }//end of for loop
        return null; //No matching resource card found
    }//end of removeCard

    public Card removeRandomCard(Random random){//CH2
        if (!resourceHand.isEmpty()){
            int randomCardIndex = random.nextInt(getTotalCardCount());
            Card randomCard = resourceHand.remove(randomCardIndex);

            ResourceType type = getTypeFromCard(randomCard);
            resourceCount[type.getIndex()]--;

            return randomCard;
        }
        return null; //player has no resource cards left
    }//end of removeCard

    private ResourceType getTypeFromCard(Card c){
        return ResourceType.valueOf(c.getCardType());
    }

    public int[] getResourceCount(){ //CH - new method
        return resourceCount;
    }

    //Displaying the resourceHand of a Trader
    public String getHandString() {
        if (resourceHand.isEmpty()) return "[Empty]";

        StringBuilder sb = new StringBuilder();
        ResourceType[] types = ResourceType.values();
        for (ResourceType type : types) {
            if (type == ResourceType.DESERT) continue;
            int count = resourceCount[type.getIndex()];
            if (count > 0) {
                sb.append(type).append(": ").append(count).append(" | ");
            }
        }
        return sb.toString();
    }

    public int getTotalCardCount(){//CH2
        return resourceHand.size();
    }
}//end of Trader


