// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/

import java.util.Scanner;

/**
 * This class represents an agent, or a player in the simulated catan game. 
 */
public abstract class Agent extends Trader{

	private int id;
	private int victoryPoints;
	private int roadsLeft;
	private int citiesLeft;
	private int settlementsLeft;
	private int infraCount;
	private Infrastructure[] infrastructure;


	public Agent(int id){
		this.id = id;
		this.roadsLeft = 15;
		this.citiesLeft = 4;
		this.settlementsLeft = 5;
		this.infraCount = 0;
		this.victoryPoints = 0;
        this.infrastructure = new Infrastructure[24];
	}

	public void buildRoad(Location location){
		if (roadsLeft <= 0){
			throw new IllegalStateException("There are no roads left to build. Sorry!");
		}

		Road road = new Road(this);
		road.build(location);

		infrastructure[infraCount++] = road;
		roadsLeft--;
	}

	public void buildCity(Location location){
		if (citiesLeft <= 0){
			throw new IllegalStateException("There are no cities left to build. Sorry!");
		}

		City city = new City(this);
		city.build(location);

		infrastructure[infraCount++] = city;
		citiesLeft--;
	}

	public void buildSettlement(Location location){
		if (settlementsLeft <= 0){
			throw new IllegalStateException("There are no settlements left to build. Sorry!");
		}

		Settlement settlement = new Settlement(this);
		settlement.build(location);

		infrastructure[infraCount++] = settlement;
		settlementsLeft--;
		this.victoryPoints--; //a settlement gives 1 VP and a city gives 2 VP, but after the settlement is upgraded 
							  // to a city, it looses the 1 VP from the old settlement. Or we can change this in City class
		
	}

	private int calculateVictoryPoints(){
		int total = 0;
		for (int i=0; i< infraCount; i++){
			total += infrastructure[i].getVictoryPoints();
		}

		this.victoryPoints = total;
		return victoryPoints;
	}

	public boolean canAfford(int toBuild) {
		// 0: Road, 1: Settlement, 2: City
		ResourceType[][] costs = {
				{ResourceType.BRICK, ResourceType.LUMBER},
				{ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL},
				{ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE}
		};

		// Bounds check to prevent crashes
		if (toBuild < 0 || toBuild >= costs.length) return false;

		ResourceType[] recipe = costs[toBuild];

		// We use getResourceCount() which returns the int[] array
		int[] original = this.getResourceCount();
		int[] temp = new int[original.length];

		// Copy current counts to a temp array so we don't accidentally deduct them
		System.arraycopy(original, 0, temp, 0, original.length);

		for (ResourceType type : recipe) {
			int index = type.getIndex();
			temp[index]--;

			if (temp[index] < 0) {
				return false; // Not enough of this resource
			}
		}
		return true; // Agent has everything required
	}


	public int getVictoryPoints(){
		return calculateVictoryPoints(); //calls the helper method above to get the victoryPoints
	}

	public int getInfraCount(){
		return infraCount;
	}

    public int getId(){ //CH - new method
        return id;
    }

    public Infrastructure[] getInfrastructure(){//CH
        return infrastructure;
    }

	//Methods to be overriden in HumanAgent and RandomAgent
	public abstract void takeTurn(Game game, Scanner scanner);


}
