// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * An interface to define the behaviour of a card in the game. All cards must be able to return their type. 
 */
public interface Card{
	public String getCardType();
}
