// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * A concrete subclass of infrastructure. A type of infrastructure worth 2 VP that can be built by a player.
 */
public class City extends Infrastructure{
    public City(Agent owner){
        super(2, owner); //City gives 2 VP
    }

    @Override
    public void build(Location location) {
        if (!(location instanceof Node)) {
            throw new IllegalStateException("A city must be placed on a Node.");
        }

        //Update the location
        super.setLocation(location);

    }

    @Override
    public String getInfraName(){
        return "CITY";
    }

}