// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Game{
    private int maxRounds;
    private int currentRound;
    private Board board;
    private Trader[] agents;
    private Trader bank;

    private Dice dice;

    //CH - add CurentPlayer
    private Trader currentPlayer;

    public Game(int rounds, int numPlayers){//CH - add numPlayers
        this.maxRounds = rounds;

        if (numPlayers < 3 || numPlayers > 4) numPlayers = 4; //defaulting to 4 players.
        agents = new Agent[numPlayers];

        if (maxRounds > MapSkeleton.maxRounds) maxRounds = 8192; //default

        agents[0] = new HumanAgent(1); //first player is human

        for (int i = 1; i < numPlayers; i++){
            agents[i] = new RandomAgent(i+1); //the other players are computers
        }

        board = new Board();
        bank = new Bank();
        dice = new MultiDice(2);
    }//end of Game constructor

    public void run(Scanner scanner){
        initialSetup(scanner);

        for(currentRound = 1; currentRound <= maxRounds; currentRound++){
            for (Trader agent : agents){
                currentPlayer = agent;
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": Turn Start");

                if (agent instanceof HumanAgent){
                    ((HumanAgent) agent).takeTurn(this, scanner);
                }
                else if(agent instanceof RandomAgent){
                    ((RandomAgent) agent).takeTurn(this, scanner);
                    System.out.println("Computer turn ended. Type 'go' to move to the next player.");
                    while (true) {
                        String wait = scanner.nextLine().trim();
                        if (wait.equalsIgnoreCase("go")) {
                            break;
                        }
                    }
                }

                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": Turn End\n");
            }//end of each agent's turn

            /* Checking Victory Point status of each player */
            int winnerID = -1;
            System.out.println();
            System.out.println("Current Victory Points: ");
            for (Trader agent : agents){
                int agentVicPoints = ((Agent) agent).getVictoryPoints();
                System.out.println(currentRound + " / " + ((Agent)agent).getId() + ": " + agentVicPoints);
                if (agentVicPoints >= 10){
                    winnerID = ((Agent) agent).getId();
                    currentRound = maxRounds + 1; //breaks the rounds loop
                    break; //gets out of for each loop
                }
            }//end of for each (check each player's vicpoints)

            if (winnerID != -1){
                System.out.println(currentRound + " / " + winnerID + ": Wins Game");
            }//end of if (win message)
            System.out.println();
        }//end of for loop (max round loop)
    }//end of run()

    //NEW METHODS ADDED FOR ASSIGNMENT 2 BELOW ----- :

    //Method for parsing the input, by using REGEX
    public boolean processCommand(String input) { //return value is not used in program, but should be used for testing

        input = input.trim().toLowerCase();
        Agent player = (Agent) currentPlayer;
        int playerId = player.getId();

        // ---------- ROLL ----------
        if (input.matches("^roll$")) {
            int roll = dice.roll();
            System.out.println(currentRound + " / " + playerId + ": Rolled a " + roll); //not using printMessage because we have roll variable

            if (roll != 7) produceResource(roll);
            return true; //false ?
        }

        // ---------- LIST ----------
        if (input.matches("^list$")) {
            printMessage(player.getHandString());
            return true;
        }

        // ---------- GO ----------
        if (input.matches("^go$")) {
            return true;
        }

        // ---------- BUILD ----------
        Pattern buildPattern = Pattern.compile("^build\\s+(road|settlement|city)\\s+(\\d+)(?:\\s+(\\d+))?$");
        Matcher matcher = buildPattern.matcher(input);

        if (matcher.matches()) {

            String type = matcher.group(1); //type of build : road, settlement or city
            String first = matcher.group(2); //1st number, start node for road, or just node ID for settlement and city
            String second = matcher.group(3); // 2nd number, end node for road, null for settlement and city

            return handleBuild(type, first, second);
        }

        printMessage("Invalid command.");
        return false;
    }



    //Method for calling the right build methods accordingly, depending on the input
    //Only being called by processCommand method above
    private boolean handleBuild(String type, String first, String second) {
        Agent player = (Agent) currentPlayer;

        if (type.equals("road")) {
            if (second == null) {
                printMessage("Road requires two node IDs.");
                return false;
            }

            int a = Integer.parseInt(first);
            int b = Integer.parseInt(second);
            Edge edge = board.getEdgeByIDNodes(a, b);

            if (edge == null || !canBuildRoad(edge)) {
                printMessage("Illegal road placement.");
                return false;
            }

            if (!resourcePayement(0)) {
                printMessage("Insufficient resources.");
                return false;
            }

            player.buildRoad(edge);
            return true;
        }

        if (type.equals("settlement")) {
            int id = Integer.parseInt(first);
            Node node = board.getIDNode(id);

            if (node == null || !canBuildSettlement(node)) {
                printMessage("Illegal settlement placement.");
                return false;
            }

            if (!resourcePayement(1)) {
                printMessage("Insufficient resources.");
                return false;
            }

            player.buildSettlement(node);
            return true;
        }

        if (type.equals("city")) {
            int id = Integer.parseInt(first);
            Node node = board.getIDNode(id);

            if (node == null || !canBuildCity(node)) {
                printMessage("Illegal city placement.");
                return false;
            }

            if (!resourcePayement(2)) {
                printMessage("Insufficient resources.");
                return false;
            }

            player.buildCity(node);
            return true;
        }

        return false;
    }

    //Helper method to print; it is public because Agent subclasses use this method too
    public void printMessage(String message){
        System.out.println(currentRound + " / " + ((Agent) currentPlayer).getId() + ": " + message);
    }


    //find the hextile that has that corresponding token
    //from that hextile, get his array of nodes
    //from that, loop through the node to see if any of the node is occupied
    //if that node is occupied, then get array from each agent to get their array of infrastructure
    //from that, check if the node that we currently have (as occupied) matches any of the agent's infrastructure node (whether that is city or node)
    private void produceResource(int token){
        HexTile[] producingTiles = board.getResourceProdTile(token); //getting the relevant hextiles

        for (HexTile currTile : producingTiles){
            if (currTile != null){

                Location[] tileNodes = currTile.getNodes(); //get nodes of that tile
                ResourceType resourceType = currTile.getResourceType();

                //Loop over each agent
                for (Trader agentTrader : agents){
                    Agent agent = (Agent) agentTrader;

                    //Loop over each infrastructure of the agent
                    for (int i=0; i < agent.getInfraCount(); i++){
                        Infrastructure infra = agent.getInfrastructure()[i]; //getting each infrastructure that the agent has currently

                        //Check if that infrastructure is on this tile
                        for (Location node : tileNodes){
                            if (infra.getLocation() == node){
                                int amount = (infra instanceof City) ? 2 : 1; //if city, then it produces 2*resource, otherwise it's a settlement which gives 1*resource
                        
                                //Give the agent the resource
                                for (int j=0; j<amount; j++){
                                    Card cardFromBank = bank.removeCard(resourceType); //remove the card from the bank
                                    if (cardFromBank != null){ //checking if the bank had at least one card to give to the agent
                                        agent.addCard(cardFromBank);
                                        System.out.println(currentRound + " / " + agent.getId() + ": Receives " + resourceType);
                                    } else {
                                        System.out.println(currentRound + " / " + agent.getId() + ": Bank is out of " + resourceType + " cards");
                                    }
                                }

                                break; //stop checking for other nodes for this infra
                            }
                        }
                    }
                }
            }
        }
    }

    private boolean build(Scanner scanner){
        int buildChoice;
        do{
            String buildChoiceStr = scanner.nextLine();
            buildChoice = Integer.parseInt(buildChoiceStr.trim());

            if (buildChoice == 3){
                return false;
            }

            boolean legalBuild = false;

            if (buildChoice == 0) { // Road
                Location buildTarget = roadEdgeInput(scanner);
                legalBuild = canBuildRoad((Edge) buildTarget);

                if (!legalBuild) {
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                    return false;
                }

                //Check and deduct resources first
                if (!resourcePayement(buildChoice)) {
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Insufficient resources");
                    return false;
                }
                //Attempt to build
                try {
                    ((Agent) currentPlayer).buildRoad(buildTarget);
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Build a Road between node #" + ((Edge) buildTarget).getStart() + " and node #" + ((Edge) buildTarget).getEnd());
                    return true;   //success and resources already deducted
                }
                catch (IllegalStateException e) {
                    //Build failed so refund the resources
                    refundResources(buildChoice);
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": " + e.getMessage());
                    return false;
                }
            }//end of Road

            else if (buildChoice == 1){//Settlement
                Location buildTarget = buildingNodeInput(scanner); //get user's input for location of settlement
                legalBuild = canBuildSettlement((Node) buildTarget); //Checks if the user can build settlement at target

                if (!legalBuild){
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                    return false;
                }
                //Check and deduct resources first
                if (!resourcePayement(buildChoice)) {
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Insufficient resources");
                    return false;
                }
                //Attempt to build
                try {
                    ((Agent) currentPlayer).buildSettlement(buildTarget);
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Build a Settlement at node #" + ((Node) buildTarget).getId());
                    return true;   //success and resources already deducted
                }
                catch (IllegalStateException e) {
                    //Build failed so refund the resources
                    refundResources(buildChoice);
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": " + e.getMessage());
                    return false;
                }
            }//end building Settlement
            else if (buildChoice == 2){//City
                Location buildTarget = buildingNodeInput(scanner); //get user's input for location of settlement
                legalBuild = canBuildCity((Node) buildTarget);

                if (!legalBuild){
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                    return false;
                }

                //Check and deduct resources first
                if (!resourcePayement(buildChoice)) {
                    //System.out.println("Insufficient resources.");
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Insufficient resources");
                    return false;
                }
                //Attempt to build
                try {
                    ((Agent) currentPlayer).buildCity(buildTarget);
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Build a City at node #" + ((Node) buildTarget).getId());
                    return true;   //success and resources already deducted
                }
                catch (IllegalStateException e) {
                    //Build failed so refund the resources
                    refundResources(buildChoice);
                    //System.out.println("Build failed: " + e.getMessage());
                    System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": " + e.getMessage());
                    return false;
                }
            }//end building City

            else System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid build choice. Try Again");
                //System.out.println("Invalid choice. Try Again");
        } while (true);

    }//end of build()
    private boolean resourcePayement(int toBuild){ //CH - change to boolean return

        ResourceType[][] materials = {
                {ResourceType.BRICK, ResourceType.LUMBER}, //Road
                {ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL}, //Settlement
                {ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE} //City
        };

        ResourceType[] recipe = materials[toBuild];

        int[] original = currentPlayer.getResourceCount(); //gets player's array
        int[] temp = new int[original.length];
        //copy count over
        System.arraycopy(original, 0, temp, 0, original.length);

        for (ResourceType type : recipe){
            int index = type.getIndex();
            temp[index]--;

            if (temp[index] < 0) {
                return false;  //not enough resources
            }
        }//end of for each

        for (ResourceType type : recipe) {
            Card transitionCard = currentPlayer.removeCard(type);
            bank.addCard(transitionCard);
        }
        return true;
    }//end of build
    private void refundResources(int toBuild) {
        ResourceType[][] materials = {
                {ResourceType.BRICK, ResourceType.LUMBER},
                {ResourceType.BRICK, ResourceType.LUMBER, ResourceType.GRAIN, ResourceType.WOOL},
                {ResourceType.GRAIN, ResourceType.GRAIN, ResourceType.ORE, ResourceType.ORE, ResourceType.ORE}
        };
        ResourceType[] recipe = materials[toBuild];
        for (ResourceType type : recipe) {
            //Remove one card of this type from the bank
            Card card = bank.removeCard(type);
            //Give it back to the player
            (currentPlayer).addCard(card);
        }
    }


    private Location roadEdgeInput(Scanner s){ //CH
        Edge edge = null;

        while (edge == null){
            //System.out.print("Enter start node ID: ");

            String aStr = s.nextLine();
            int a = Integer.parseInt(aStr.trim());
            System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects start node (#" + a + ") of edge");
            //int a = s.nextInt();
            //s.nextLine();

            //System.out.print("Enter end node ID: ");
            String bStr = s.nextLine();
            int b = Integer.parseInt(bStr.trim());
            System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects end node (#" + b + ") of edge");
            //int b = s.nextLine();
            //s.nextLine();

            edge = board.getEdgeByIDNodes(a, b);

            if (edge == null) System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid node IDs. Try Again");
                //System.out.println("Invalid node IDs. Please try again."); // if edge is still null after method, the search failed
        }
        return edge;
    }
    private Location buildingNodeInput(Scanner s){//CH
        Node node = null;

        while (node == null){
            //System.out.print("Enter node ID: ");
            //int id = s.nextInt();
            String idStr = s.nextLine();
            int id = Integer.parseInt(idStr.trim());
            System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Selects node (#" + idStr + ")");
            //s.nextLine();
            //s.nextLine();

            node = board.getIDNode(id);

            if (node == null){// if node is still null after method, the search failed
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Invalid node ID. Try Again");
                //System.out.println("Invalid node ID. Please try again.");
            }
        }
        return node;
    }

    private boolean canBuildRoad(Edge edge){//CH
        Agent player = (Agent) currentPlayer; //type casting to use Agent methods, not just Trader
        if (edge.isOccupied()) return false;

        int a = edge.getStart();
        int b = edge.getEnd();

        //Check player's infrastructure
        for (int i = 0; i < player.getInfraCount(); i++) {
            Infrastructure infra = player.getInfrastructure()[i];
            Location loc = infra.getLocation();

            //Connected to player's settlement/city
            if (loc instanceof Node){
                Node n = (Node) loc;
                if (n.getId() == a || n.getId() == b) return true;
            }

            //Connected to player's road
            if (loc instanceof Edge) {
                Edge e = (Edge) loc;
                boolean isConnected = (e.getStart() == a || e.getStart() == b || e.getEnd() == a   || e.getEnd() == b);
                if (isConnected){
                    //finds the shared node ID
                    int sharedNode;
                    if (e.getStart() == a || e.getEnd() == a) sharedNode = a;
                    else sharedNode = b;

                    //If shared node is occupied by ANOTHER player - build should fail
                    for (Trader players : agents){
                        Agent enemyPlayer = (Agent) players;
                        if (enemyPlayer == player) continue; //no need to check if the node is the currplayer's or not

                        for (int j = 0; j < enemyPlayer.getInfraCount(); j++){
                            Infrastructure otherInfra = enemyPlayer.getInfrastructure()[j];

                            if (otherInfra instanceof Settlement || otherInfra instanceof City){
                                Node otherNode = (Node) otherInfra.getLocation();
                                if (otherNode.getId() == sharedNode){
                                    return false; //build has been blocked by enemy building
                                }
                            }
                        }//end of for loop
                    }
                    return true;
                }
            }
        }//end of for loop (checking player's infrastructures)
        return false;
    }//end of canBuildRoad

    private boolean canBuildSettlement(Node node){ //Ch
        Agent player = (Agent) currentPlayer;
        if (node.isOccupied()) return false;

        int nodeId = node.getId();

        //must connect to player's existing road
        boolean connectedToRoad = false;

        for (int i = 0; i < player.getInfraCount(); i++) {
            Infrastructure infra = player.getInfrastructure()[i];

            if (infra instanceof Road){
                Edge e = (Edge) infra.getLocation();

                if (e.getStart() == nodeId || e.getEnd() == nodeId) {
                    connectedToRoad = true;
                    break;
                }
            }
        }//end of for loop (checking player's infrastructures)

        if (!connectedToRoad) return false;

        if (!noAdjacentSettlements(node)) return false;

        return true;
    }//end of canBuildSettlement()

    private boolean canBuildCity(Node node){//CH
        Agent player = (Agent) currentPlayer;
        for (int i = 0; i < player.getInfraCount(); i++){
            Infrastructure infra = player.getInfrastructure()[i];
            //Checking if the infra. is a settlement and has the same location as where the player wants to place City
            if (infra instanceof Settlement && infra.getLocation() == node) return true;
        }//end of for loop (checking player's infrastructures)
        return false;
    }//end of canBuildCity()


    private void giveResourceInitialSetup(Node node, Trader currentPlayer){
        Agent player = (Agent) currentPlayer;
        
        for (HexTile tile : board.getTiles()){
            Location[] tileNodes = tile.getNodes();

            for (Location tileNode : tileNodes){
                if (tileNode == node){
                    ResourceType type = tile.getResourceType();
                    if(type != ResourceType.DESERT){
                        Card card = bank.removeCard(type);

                        if(card != null){
                            System.out.println(currentRound + " / " + player.getId() + ": Receives " + type);
                            player.addCard(card);
                        }
                    }
                    break;
                }
            }
        }
    }

    private void initialSetup(Scanner scanner){
        //Forward order
        for (Trader agent : agents){
            executeSetupTurn(agent, scanner, "Initial");
            System.out.println();
        }//end of forward turn order of players
        System.out.println();
        //Reverse Order
        for (int i = agents.length - 1; i >= 0; i--){
            executeSetupTurn(agents[i], scanner, "Secondary");
        }//end of backwards turn order of players
    }//end of initialSetup()

    //Created this helper method for initialSetup method, to avoid duplicate code for forward and reverse order
    private void executeSetupTurn(Trader agent, Scanner scanner, String phase){
        currentPlayer = agent;
        Agent a = (Agent) agent;
        System.out.println(currentRound + " / " + a.getId() + ": Selecting " + phase + " Settlement and Road");

        Node settlementSpot = null;
        Edge roadSpot = null;

        if (a instanceof HumanAgent){
            settlementSpot = setupSettlementInput(scanner);
            roadSpot = setupRoadInput(scanner, settlementSpot);
        }
        else if (agent instanceof RandomAgent){
            settlementSpot = findRandomValidSettlement();
            roadSpot = findRandomValidRoad(settlementSpot);
        }
        a.buildSettlement(settlementSpot);
        a.buildRoad(roadSpot);
        System.out.println(currentRound + " / " + a.getId() + ": Placed " + phase + " Infrastructure");

        if (phase.equals("Secondary") && settlementSpot != null){
            giveResourceInitialSetup(settlementSpot, agent);
        }
    }

    private Node findRandomValidSettlement() {
        List<Node> validNodes = new ArrayList<>();
        // We get all nodes, so we are iterating 0 to 53
        for (int i = 0; i < 54; i++) {
            Node n = board.getIDNode(i);
            if (n != null && !n.isOccupied() && noAdjacentSettlements(n)) {
                validNodes.add(n);
            }
        }
        // Pick one randomly from all valid nodes that we have added
        return validNodes.get(new java.util.Random().nextInt(validNodes.size()));
    }

    private Edge findRandomValidRoad(Node settlement) {
        List<Edge> validEdges = new ArrayList<>();
        int nodeId = settlement.getId();

        // Check all edges in the MapSkeleton
        for (int[] e : MapSkeleton.edges) {
            if (e[0] == nodeId || e[1] == nodeId) {
                Edge edge = board.getEdgeByIDNodes(e[0], e[1]);
                if (edge != null && !edge.isOccupied()) {
                    validEdges.add(edge);
                }
            }
        }
        // Pick one randomly from all valid edges that we have added
        return validEdges.get(new java.util.Random().nextInt(validEdges.size()));
    }




    private Node setupSettlementInput(Scanner scanner){
        while (true){
            Node node = (Node) buildingNodeInput(scanner);
            if (node.isOccupied() || !noAdjacentSettlements(node)){
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                continue; //Get user input again
            }

            return node;
        }
    }//end of setupSettlementInput

    private Edge setupRoadInput(Scanner scanner, Node settlement){
        while (true){
            Edge edge = (Edge) roadEdgeInput(scanner);
            if (edge.isOccupied()){
                System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
                continue;
            }
            int a = edge.getStart();
            int b = edge.getEnd();

            if (a == settlement.getId() || b == settlement.getId()){
                return edge;
            }
            System.out.println(currentRound + " / " + ((Agent)currentPlayer).getId() + ": Illegal build");
        }
    }//end of setupRoadInput()

    private boolean noAdjacentSettlements(Node node){
        int nodeId = node.getId();

        for (int[] e : MapSkeleton.edges){
            if (e[0] == nodeId || e[1] == nodeId){

                int neighborId;
                if (e[0] == nodeId) neighborId = e[1];
                else neighborId = e[0];

                Node neighbor = board.getIDNode(neighborId);
                if (neighbor.isOccupied()) return false;
            }
        }
        return true;
    }//end of noAdjacentSettlements()

//    public Dice getDice() {
//        return dice;
//    }
}//end of Game class